export { default as img00 } from "../../assets/images/animations/break/destroy_stage_0.png";
export { default as img01 } from "../../assets/images/animations/break/destroy_stage_1.png";
export { default as img02 } from "../../assets/images/animations/break/destroy_stage_2.png";
export { default as img03 } from "../../assets/images/animations/break/destroy_stage_3.png";
export { default as img04 } from "../../assets/images/animations/break/destroy_stage_4.png";
export { default as img05 } from "../../assets/images/animations/break/destroy_stage_5.png";
export { default as img06 } from "../../assets/images/animations/break/destroy_stage_6.png";
export { default as img07 } from "../../assets/images/animations/break/destroy_stage_7.png";
export { default as img08 } from "../../assets/images/animations/break/destroy_stage_8.png";
