name: Publish  

on:
    workflow_call:
      inputs:
        deploy_android:
          description: "Deploy Android application"
          required: true
          default: true
          type: boolean
        deploy_ios:
          description: "Deploy iOS application"
          required: true
          default: true
          type: boolean
        internal_testing:
          description: "Deploy to internal testing"
          required: true
          default: true
          type: boolean
        ref:
          description: "Git reference to deploy"
          required: true
          default: "main"
          type: string

jobs:
    deploy-android:
        if: ${{ inputs.deploy_android == true }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: npm
                cache-dependency-path: "./frontend/package.json"

            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci

            - name: Decode Keystore
              working-directory: ./frontend
              env:
                KEYSTORE_ENCODED: ${{ secrets.KEYSTORE_ENCODED }}
              run: 
                echo $KEYSTORE_ENCODED | base64 --decode > ${{ secrets.KEYSTORE_FILE_NAME }}

            - name: Prebuild app
              working-directory: ./frontend
              env:
                KEYSTORE_FILE_NAME: ${{ secrets.KEYSTORE_FILE_NAME }}
                KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
                KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
                KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
              run: npx expo prebuild --platform android

            - name: Move keystore into app folder
              working-directory: ./frontend
              run: mv ${{ secrets.KEYSTORE_FILE_NAME }} android/app/${{ secrets.KEYSTORE_FILE_NAME }}

            - name: Build Android (APK)
              if: ${{ inputs.internal_testing == true }}
              working-directory: ./frontend/android
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: ./gradlew app:assembleRelease

            - name: Upload to Firebase
              if: ${{ inputs.internal_testing == true }}
              uses: wzieba/Firebase-Distribution-Github-Action@v1
              with:
                appId: ${{ secrets.FIREBASE_APP_ID }}
                serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
                groups: internal-testers
                file: "./frontend/android/app/build/outputs/apk/release/app-release.apk"

            - name: Build Android (AAB)
              if: ${{ inputs.internal_testing == false }}
              working-directory: ./frontend/android
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: ./gradlew app:bundleRelease

            - name: Upload to Google Play
              uses: r0adkll/upload-google-play@v1
              if: ${{ inputs.internal_testing == false }}
              with:
                serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
                packageName: com.starknet.pow
                releaseFiles: ./frontend/android/app/build/outputs/bundle/release/app-release.aab
                track: production
                status: draft

    deploy-ios:
      if: ${{ inputs.deploy_ios == true }}
      runs-on: macos-latest
      steps:
            - name: Checkout project
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: npm
                cache-dependency-path: "./frontend/package.json"

            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci

            - name: Prebuild app
              working-directory: ./frontend
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: npx expo prebuild --platform ios
            
            - name: Install certificate and provisioning profile
              working-directory: ./frontend
              env:
                IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
                IOS_P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
                IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
                IOS_KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
              run: |
                # Create temporary paths for certificate, provisioning profile and keychain
                CERTIFICATE_PATH=$RUNNER_TEMP/certificate.p12
                PROVISIONING_PROFILE_PATH=$RUNNER_TEMP/pp.mobileprovision
                KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

                # Decode certificate and provisioning profile
                echo -n "$IOS_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
                echo -n "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PROVISIONING_PROFILE_PATH

                # Create keychain and set settings
                security create-keychain -p "$IOS_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
                security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
                security unlock-keychain -p "$IOS_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

                # Import certificate and provisioning profile
                security import $CERTIFICATE_PATH -P "$IOS_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
                security list-keychain -d user -s $KEYCHAIN_PATH

                # Copy provisioning profile to library
                mkdir -p ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
                cp $PROVISIONING_PROFILE_PATH ~/Library/Developer/Xcode/UserData/Provisioning\ Profiles
            
            - name: Build archive
              working-directory: ./frontend/ios
              env:
                IOS_DEVELOPMENT_TEAM: ${{ secrets.IOS_DEVELOPMENT_TEAM }}
              run: |
                xcodebuild -workspace POW.xcworkspace \
                -scheme "POW" \
                -archivePath $RUNNER_TEMP/POW.xcarchive \
                -sdk iphoneos \
                -configuration Release \
                -destination generic/platform=iOS \
                -allowProvisioningUpdates DEVELOPMENT_TEAM=$IOS_DEVELOPMENT_TEAM \
                -resultBundlePath $RUNNER_TEMP/result \
                clean archive

            - name: Upload result (when failed)
              if: ${{ failure() }}
              uses: actions/upload-artifact@v4
              with:
                name: POW-build-result
                path: "${{ runner.temp }}/result/result.xcresult"
            
            - name: Upload IPA
              env:
                IOS_EXPORT_OPTIONS_PLIST: ${{ secrets.IOS_EXPORT_OPTIONS_PLIST }}
              run: |
                EXPORT_OPTS_PATH=$RUNNER_TEMP/ExportOptions.plist
                echo -n "$IOS_EXPORT_OPTIONS_PLIST" | base64 --decode -o $EXPORT_OPTS_PATH
                
                xcodebuild -exportArchive \
                -archivePath $RUNNER_TEMP/POW.xcarchive \
                -exportOptionsPlist $EXPORT_OPTS_PATH \
                -exportPath $RUNNER_TEMP/build
            