name: Publish  

on:
    workflow_call:
      inputs:
        deploy_android:
          description: "Deploy Android application"
          required: true
          default: true
          type: boolean
        deploy_ios:
          description: "Deploy iOS application"
          required: true
          default: true
          type: boolean
        internal_testing:
          description: "Deploy to internal testing"
          required: true
          default: true
          type: boolean
        ref:
          description: "Git reference to deploy"
          required: true
          default: "main"
          type: string

jobs:
    deploy-android:
        if: ${{ inputs.deploy_android == true }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout project
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: npm
                cache-dependency-path: "./frontend/package.json"

            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci

            - name: Decode Keystore
              working-directory: ./frontend
              env:
                KEYSTORE_ENCODED: ${{ secrets.KEYSTORE_ENCODED }}
              run: 
                echo $KEYSTORE_ENCODED | base64 --decode > ${{ secrets.KEYSTORE_FILE_NAME }}

            - name: Prebuild app
              working-directory: ./frontend
              env:
                KEYSTORE_FILE_NAME: ${{ secrets.KEYSTORE_FILE_NAME }}
                KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
                KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
                KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
              run: npx expo prebuild --platform android

            - name: Move keystore into app folder
              working-directory: ./frontend
              run: mv ${{ secrets.KEYSTORE_FILE_NAME }} android/app/${{ secrets.KEYSTORE_FILE_NAME }}

            - name: Build Android (APK)
              if: ${{ inputs.internal_testing == true }}
              working-directory: ./frontend/android
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: ./gradlew app:assembleRelease

            - name: Upload to Firebase
              if: ${{ inputs.internal_testing == true }}
              uses: wzieba/Firebase-Distribution-Github-Action@v1
              with:
                appId: ${{ secrets.FIREBASE_APP_ID }}
                serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
                groups: internal-testers
                file: "./frontend/android/app/build/outputs/apk/release/app-release.apk"

            - name: Build Android (AAB)
              if: ${{ inputs.internal_testing == false }}
              working-directory: ./frontend/android
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: ./gradlew app:bundleRelease

            - name: Upload to Google Play
              uses: r0adkll/upload-google-play@v1
              if: ${{ inputs.internal_testing == false }}
              with:
                serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
                packageName: com.starknet.pow
                releaseFiles: ./frontend/android/app/build/outputs/bundle/release/app-release.aab
                track: production
                status: draft

    deploy-ios:
      if: ${{ inputs.deploy_ios == true }}
      runs-on: macos-15
      steps:
            - name: Checkout project
              uses: actions/checkout@v4
              with:
                ref: ${{ inputs.ref }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: latest
                cache: npm
                cache-dependency-path: "./frontend/package.json"

            - name: Install dependencies
              working-directory: ./frontend
              run: npm ci

            - name: Prebuild app
              working-directory: ./frontend
              env:
                SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              run: npx expo prebuild --platform ios
            
            - name: Setup Fastlane scripts
              working-directory: ./frontend
              run: |
                mv ./scripts/ios/* ./ios/

            - name: Update Gems
              working-directory: ./frontend/ios
              run: bundle update

            - name: Decode App Store Connect Key
              working-directory: ./frontend/ios
              env:
                APPSTORE_CONNECT_KEY_ENCODED: ${{ secrets.APPSTORE_CONNECT_KEY_BASE64 }}
              run: |
                echo $APPSTORE_CONNECT_KEY_ENCODED | base64 --decode > ${{ secrets.APPSTORE_CONNECT_KEY_FILE_PATH }}

            - name: Import Certificate
              working-directory: ./frontend/ios
              env:
                APPSTORE_CERTIFICATE_BASE64: ${{ secrets.APPSTORE_CERTIFICATE_BASE64 }}
                APPSTORE_CERTIFICATE_PASSWORD: ${{ secrets.APPSTORE_CERTIFICATE_PASSWORD }}
                KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
                KEYCHAIN_PATH: ./temp.keychain-db
              run: |
                CERTIFICATE_PATH=certificate.p12
                echo "$APPSTORE_CERTIFICATE_BASE64" | base64 --decode > $CERTIFICATE_PATH

                # create temporary keychain
                security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
                security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
                security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

                security import $CERTIFICATE_PATH -P $APPSTORE_CERTIFICATE_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
                security list-keychain -d user -s $KEYCHAIN_PATH

                rm $CERTIFICATE_PATH

            - name: Deploy to Testflight
              if: ${{ inputs.internal_testing == true }}
              working-directory: ./frontend/ios
              env:
                APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
                APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
                APPSTORE_CONNECT_KEY_FILE_PATH: ${{ secrets.APPSTORE_CONNECT_KEY_FILE_PATH }}
                KEYCHAIN_PATH: "./temp.keychain-db"
                KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
              run: bundle exec fastlane deploy_testflight

            - name: Deploy to App Store
              if: ${{ inputs.internal_testing == false }}
              working-directory: ./frontend/ios
              env:
                APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
                APPSTORE_CONNECT_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_ISSUER_ID }}
                APPSTORE_CONNECT_KEY_FILE_PATH: ${{ secrets.APPSTORE_CONNECT_KEY_FILE_PATH }}
                KEYCHAIN_PATH: "temp.keychain-db"
                KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
              run: bundle exec fastlane deploy