name: Release

# on: 
#     release:
#         types: [published]
on:
    push:
        branches:
            - cd/ios
            

jobs:
    run-deploy:
        uses: ./.github/workflows/deploy-mobile.yml
        secrets: inherit
        with:
            deploy_android: false
            deploy_ios: true
            internal_testing: ${{ github.event.release.prerelease }}
            ref: ${{ github.event.release.target_commitish }}