name: Release

on: 
    release:
        types: [published]

jobs:
    run-deploy:
        uses: ./.github/workflows/deploy-mobile.yml
        secrets: inherit
        with:
            deploy_android: true
            deploy_ios: true
            internal_testing: ${{ github.event.release.prerelease }}
            ref: ${{ github.ref }}