name: Release

# on: 
#     release:
#         types: [published]

on:
    push:
        branches:
            - env/setup

jobs:
    run-deploy:
        uses: ./.github/workflows/deploy-mobile.yml
        secrets: inherit
        with:
            deploy_android: true
            deploy_ios: false
            internal_testing: true
                # ${{ github.event.release.prerelease }}
            version: "0.1.2"
                # ${{ github.event.release.name }}
            ref: ${{ github.ref }}