name: Temporary Workflow

on: 
    push:
        branches:
            - build/firebase

jobs:
    run-deploy:
        uses: ./.github/workflows/deploy-mobile.yml
        secrets: inherit
        with:
            deploy_android: true
            deploy_ios: false
            internal_testing: true